### ISSUE TITLE
GraphQL Support

### ISSUE THREAD

**Issue by ShayneP** [christophergregory/shopify-node-api#100]
Shopify is doubling down on GraphQL, and we'd love to keep recommending shopify-node-api.

We're suggesting that libraries add the ability to make queries to the Shopify API in GraphQL, and since shopify-node-api is one of the more popular libraries for Node, we were hoping you'd be able to add it to your roadmap.

If @christophergregory is too busy, and anyone in the community wants to work on this with me, either comment below or email me at shayne@shopify.com and I'd love to talk.

**Comment by nodeit** [comment]
Hey Shayne, 

I'm thrilled that this library has helped so many and continues to do so. Unfortunately, as you suspected, I have far too much on my plate to update it to include GraphQL. 

With that said, I am more than happy to accept merge requests or even add admin access to the repo for someone who has the time.

If you or anyone you recommend would like access just send them my way and I'll get it done.

Thanks!

**Comment by ShayneP** [comment]
Closed now that support is added, thanks everyone.
