### ISSUE TITLE
Please add pagination support

### ISSUE THREAD

**Issue by mariusa** [christophergregory/shopify-node-api#104]
There's a new way to work with pagination:
https://help.shopify.com/en/api/guides/paginated-rest-results

Would you please have built-in support for this?

An idea: "options" is already returned on Shopify.get() as a 4th parameter:
https://github.com/christophergregory/shopify-node-api/blob/master/lib/shopify.js#L245
Adding "page_info_next", "page_info_previous" in this object would be very handy.

Thanks!

**Comment by AirtonSth** [comment]
Did you manage to change this package to work with new pagination?
