### ISSUE TITLE
OAuth API Endpoint Changes to Signature Verification

### ISSUE THREAD

**Issue by mariusa** [christophergregory/shopify-node-api#23]
Hello,

Does the library need to be updated for
https://ecommerce.shopify.com/c/api-announcements/t/oauth-api-endpoint-changes-to-signature-verification-222656
?
(didn't find "hmac" in code)

Thanks

**Comment by nodeit** [comment]
@mariusa Yes, it appears that it does. I should have time over the next few days to review the requirements and update the library. 

I've only briefly looked at the requirements but it doesn't appear to require breaking changes which is good.

**Comment by mariusa** [comment]
@nodeit thanks! Just a quick reminder -- there are 20 days left until the current auth will stop working.

**Comment by nodeit** [comment]
No worries, it is absolutely on my radar and I will have it updated over the next few days.

**Comment by nodeit** [comment]
I went ahead and fixed this on my lunch break :)

**Comment by mariusa** [comment]
Ha :) Thanks, and hope you still had plenty of time for lunch!
