### ISSUE TITLE
GET + Options

### ISSUE THREAD

**Issue by rafaelfaria** [christophergregory/shopify-node-api#26]
I'm trying to put a get to the products.json based on its documentation and passing the options but it's not working.

[Shopify API products.json endpoint](https://docs.shopify.com/api/product#index)

```
	Shopify.get('/admin/products.json', {fields: 'id, title', page: 1, limit: 5 }, function(err, data, headers){
			console.log(data); // Data contains product json information
			console.log(headers); // Headers returned from request
		});
```

This return ALL the products, not only 5 from page 1. What am I doing wrong? 

If i do the below, it works.

```
Shopify.get('/admin/products.json?limit=5', function(err, data, headers){
	console.log(data); // Data contains product json information
	console.log(headers); // Headers returned from request
}))
```

Thanks

**Comment by nodeit** [comment]
Your first attempt didn't work because the get method only accepts two parameters (url and a callback function). Your second attempt is the proper way to add query fields while using this module.

**Comment by rafaelfaria** [comment]
The only reason I tried to do that, is because reading the source code, the get parameter actually accepts a data object.

```

ShopifyAPI.prototype.get = function(endpoint, data, callback) {
    if (typeof data === 'function' && arguments.length < 3) {
        callback = data;
        data = null;
    }
    this.makeRequest(endpoint,'GET', data, callback);
};
```

It would be actually good if we could pass it as an object and it would convert it on your lib instead of doing it outside. I will try to create a pull request to see if you agree with it.

**Comment by nodeit** [comment]
I'm always happy to review pull requests, they are extremely helpful. However, keep in mind that this particular change would probably result in a breaking change due to the additional `options` parameter. 

I'm not saying that it isn't a good idea, but so far you are the only person to have requested this change so I'm not sure the demand is there to justify the work it would require for everyone to have to upgrade a major version in the future.

**Comment by halleycarleton** [comment]
+1
I see no reason this feature would need to add breaking changes. There would not need to be any additional options parameter as far as I can tell. You would just need to parse the object into a querystring and append it to the endpoint.
