### ISSUE TITLE
Include more query params when computing HMAC signature

### ISSUE THREAD

**Issue by mariusa** [christophergregory/shopify-node-api#30]
Hello,

We had an issue with Shopify auth sending more query params, and resulting in an invalid HMAC.

That being said, you should consider almost all url query params (**see below) to re-generate the hmac value. Not just shop and timestamp. This allows us to send you extra params when they may be required, without you needing to make a code change. 
** Your code should remove hmac and signature from the url query params.

This 
https://github.com/christophergregory/shopify-node-api/blob/master/lib/shopify.js#L54
should be changed to exclude hmac and signature, rather than including only a pre-defined list of params.

Thanks!

**Comment by nodeit** [comment]
Do you mind submitting a pull request for this? I won't be able to get to this for the next several days.

**Comment by mariusa** [comment]
I won't be able this time, sorry Chris! 
It can wait, no problem.

**Comment by NoxHarmonium** [comment]
I tried this in a fork and I am still getting a signature verification error when extra query params are added to the URL.

Here is a link to the change:
https://github.com/NoxHarmonium/shopify-node-api/commit/c9c80b930021806752ed6480c45791758d2a9197

Can you see anything wrong with it?

**Comment by mariusa** [comment]
>I am still getting a signature verification error when extra query params are added to the URL.

Can you temporarily log parameters list to make sure the right ones are included?
