### ISSUE TITLE
webhooks SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by thierryskoda** [christophergregory/shopify-node-api#36]
Hi, 

Does anyone ever had this error : "SyntaxError: Unexpected token <" in the callback "err" after trying to 
create a webhook? Here's my code 

```javascript
var topics = ['app/uninstalled', 'orders/fulfilled', 'orders/paid'];
var requesturl = "https://THESHOPURL/admin/webhooks";
Shopify.post(requesturl, { webhook : { address : config.shopify_webhook_url + topics[0] , topic : topics[0]}},
                function(err, data, headers) {
                    if(err) {
                        console.log("HEADERS : ", headers);
                        console.error("ERROR IN CREATING SHOPIFY WEBHOOKS FOR THE SHOP: ", shop.url);
                        console.error("ERR : ", err);
                    } else {
                        console.log("webhook created with ", shop.url);
                        shop.webhooks.push(data.webhook);
                    }
                }
})
```

ERROR IN CREATING SHOPIFY WEBHOOKS FOR THE SHOP: kollectionk.com
ERR : SyntaxError: Unexpected token <

**Comment by thierryskoda** [comment]
I also have 
ERR:  { error: 'Internal Server Error', code: 500 }

**Comment by nodeit** [comment]
I believe your `requesturl` is incorrect. Should be `https://THESHOPURL/admin/webhooks.json`

Notice the *.json* extension. Otherwise you are requesting a html document which of course starts with a "<".

I'm going to mark this as closed but please feel free to re-open if that wasn't the issue.

**Comment by thierryskoda** [comment]
Thank you , ya it seems to work now
