### ISSUE TITLE
Error code 404, not found

### ISSUE THREAD

**Issue by thierryskoda** [christophergregory/shopify-node-api#37]
HI, 

In my application, when a shop download my app, I create some webhooks. Sometimes it works, sometimes not. I recently had this error with a shop that I tried to create webhook { error: 'Not Found', code: 404 }. I don't know why I receive this because I have the correct access_token. I'm using this var to make request.

var Shopify = new shopifyAPI({
            shopify_api_key: process.env.SHOPIFY_API_KEY, // Your API key
            shopify_shared_secret:  process.env.SHOPIFY_SHARED_SECRET, // Your Shared Secret
            access_token: shop.access_token,
            shop: shopGoodUrl,
            verbose: false
        });

  
I think the problem is when in the library, when I make a request, the method "hostname()" is called and this method add .myshopify to the shop. For example "whatyouvape" download my app and www.whatyouvap.com works but not www.whatyouvape.myshopify.com. When I type that in the url it's says "Sorry, this shop is currently unavailable."

If someone could help me with this. This  would be very appreciated. 

Thank you very much.

**Comment by nodeit** [comment]
The shopify API expects you to use the shopify hostname, e.g. `MYSHOPNAME.myshopify.com` and not the shops domain name, e.g. `www.MYSHOPNAME.com`. 

The hostname method will work correctly if you supply it with `MYSHOPNAME.myshopify.com`.

**Comment by thierryskoda** [comment]
Yea I understand that correctly. That's why the "shopGoodUrl" is always only the MYSHOPNAME.
But even if I do this, this doesn't work sometimes and returns me error 404 : not found.

**Comment by nodeit** [comment]
Can you send me the section of code you are using to make the request?

**Comment by thierryskoda** [comment]
var shopUrlArray = shop.url.split(".");
        var shopGoodUrl = "";
        var topics = ['app/uninstalled', 'orders/fulfilled', 'orders/paid'];

        if(shopUrlArray[0] === 'www') {
            shopGoodUrl = shopUrlArray[1];
        } else {
            shopGoodUrl = shopUrlArray[0];
        }

        var requesturl = '/admin/webhooks.json';
        var Shopify = new shopifyAPI({
            shopify_api_key: process.env.SHOPIFY_API_KEY, // Your API key
            shopify_shared_secret:  process.env.SHOPIFY_SHARED_SECRET, // Your Shared Secret
            access_token: shop.access_token,
            shop: shopGoodUrl,
            verbose: true
        });

        console.log("the shopify var :", Shopify);

        function createWebhooks(i) {
            if(i < topics.length) {
                var options = {
                    address: config.shopify_webhook_url + topics[i],
                    topic: topics[i],
                    format : 'json'
                }

                console.log("the option for the webhook :", options);
                console.log("the requesturl for the webhook :", requesturl);

                Shopify.post(requesturl, { webhook : options },
                function(err, data, headers) {
                    if(err) {
                        console.error("ERROR IN CREATING SHOPIFY WEBHOOKS ERR: ", err );
                    } else {
                        console.log("webhook created with ", shop.url);
                        shop.webhooks.push(data.webhook);
                    }

                    createWebhooks(i+1);
                });
            } else {
                shop.save();
            }
        }
        createWebhooks(0);

**Comment by nodeit** [comment]
Let's reduce the code a bit so we can narrow down the problem. Can you replace your information in this code and verify that it works?

~~~
var shopifyAPI = require('shopify-node-api');

var Shopify = new shopifyAPI({
    shopify_api_key: '',
    shopify_shared_secret: '',
    access_token: '',
    shop: '',
    verbose: false
});

var webhook_url = '';

var endpoint = '/admin/webhooks.json';
var topic = 'app/uninstalled';

var options = { 
    'webhook' : {
        address: webhook_url + topic,
        topic: topic,
        format: 'json'
    }
};

var callback = function(err, data, headers) {
    if (err) return console.log('Error:', err);
    console.log(data);
};

Shopify.post(endpoint, options, callback);
~~~

**Comment by thierryskoda** [comment]
When I use this code. It gives me : 

ERROR :  { [Error: getaddrinfo ENOTFOUND .myshopify.com .myshopify.com:443]
   errno: 'ENOTFOUND',
   syscall: 'getaddrinfo',
   hostname: '.myshopify.com',
   host: '.myshopify.com',
   port: 443 
}

**Comment by nodeit** [comment]
Can you send me the exact code you used without any of the personal info? If it's returning a 404 that sounds like the module is working but that you simply aren't hitting the correct endpoint.

**Comment by thierryskoda** [comment]
I think I just found the problem ! I wasn't saving the good shopify_domain url in my database. I need to make the request on the shopify url and not the MAIN url of the website. I'm think this is the problem. I'm working on it and should find out if this was the problem really soon! 

Thank you very much! Thierry

**Comment by nodeit** [comment]
No problem at all Thierry! 

I'm going to close the issue for now then, feel free to open a new one if you still don't figure it out.
