### ISSUE TITLE
Your module is ignoring the "state" parameter which is strongly recommended by Shopify

### ISSUE THREAD

**Issue by Pixelik** [christophergregory/shopify-node-api#38]
I'm using your module and it works just fine. However, I noticed that in your signature validation you are not using the "state" parameter (which is strongly recommended by Shopify).

Why is that and does that make my app more vulnerable to hacking ?

**Comment by nodeit** [comment]
Although the state parameter is part of the OAuth 2.0 spec, it appears to have been recently added to Shopify as this is the first I'm hearing of it.

So as of write now, the the module is vulnerable to the following:

> 3.6.  "state" Parameter
> 
> The "state" parameter is used to link requests and callbacks to
> prevent cross-site request forgery attacks (see Section 4.4.1.8)
> where an attacker authorizes access to his own resources and then
> tricks a user into following a redirect with the attacker's token.
> This parameter should bind to the authenticated state in a user agent
> and, as per the core OAuth spec, the user agent must be capable of
> keeping it in a location accessible only by the client and user
> agent, i.e., protected by same-origin policy.

I will update this as soon as I get the chance. I also accept pull requests if you already have a solution.

**Comment by Pixelik** [comment]
Thanks for your quick reply. It's good to know. I'm now using my own custom signature validation (where I verify the nonce as well) in conjunction with your module and it's working.

I don't trust my Github skills enough to meddle with your code so I'll let you update it yourself whenever you find the chance :-)

Thanks!

**Comment by frehner** [comment]
Created PR #39 which I believe should resolve this issue.
