### ISSUE TITLE
Not able to redirect to auth_url

### ISSUE THREAD

**Issue by tanvee-gujral** [christophergregory/shopify-node-api#40]
Hi, I am new to shopify and node as well. I have successfully created auth url. Now i am stuck in res.redirect(url). I guess it needs login credentials  of my shop. When i am hitting this auth url on browser, it is redirecting to login page.

**Comment by nodeit** [comment]
Can you show you me the url that it is outputting? You can hide your shop name or any sensitive information of course.

**Comment by tanvee-gujral** [comment]
This is my url 
https://posist1.myshopify.com/admin/oauth/authorize?client_id="api key"
0d20&scope=write_products,read_products&redirect_uri=https://localhost:9000/test&state=tan
vee

**Comment by tanvee-gujral** [comment]
even if i redirect to above stated url through browser, i successfully get code which will be used to get permanent access token. Now if i use your function Shopify.exchange_temporary_token()

**Comment by nodeit** [comment]
Hmm, is it possible for you to privately send the relevant part of your codebase to me, sans any credentials or sensitive information.

I'm not seeing anything looks in correct on your side.

**Comment by tanvee-gujral** [comment]
Can u share ur mail I'd so that I can share the credentials ?

**Comment by nodeit** [comment]
To be clear, I don't want/need any credentials/sensitive information but you can sent it too chrisctiger [at] gmail.com
