### ISSUE TITLE
JSON parsing big integers can fail

### ISSUE THREAD

**Issue by rfink** [christophergregory/shopify-node-api#42]
Using the stock JSON.parse can fail, since shopify uses bigint types for its ids, and javascript can only natively handle 2^53 - 1, whereas the bigint can go to 2^64 - 1.  As such is the case, a number larger than Number.MAX_SAFE_INTEGER would be incorrectly parsed as a different, smaller number, and would cause untold issues.  I have not seen them send back such a large number yet, but I want to plan for the future.

I'm sending a pull request to use https://github.com/sidorares/json-bigint as the JSON parsing library, it turns numbers larger than the max safe integer into "BigNumber" objects, which can easily be represented as strings.  Coming shortly.

**Comment by nodeit** [comment]
Thanks, I've merged the pull request

**Comment by rfink** [comment]
Wow, I think you set a record with response time.  Thanks!

**Comment by nodeit** [comment]
You happened to catch me up on my lunch break :)
