### ISSUE TITLE
'State' parameter not being filled - causing invalid signature

### ISSUE THREAD

**Issue by Samlilli** [christophergregory/shopify-node-api#45]
Cannot seem to get a permanent token. 'State' in query_params is returning undefined. Could this be the reason?

**Comment by Samlilli** [comment]
No `nonce` is generated and therefore no '&state=something` on the url. Any ideas why?

**Comment by Samlilli** [comment]
My bad... Thought the module provided a random 'nonce' value. Updated and now working!

Perhaps it should be clearer on the docs that this is to be provided (for dummies like myself!). To me the comment insinuated the module would randomly generate this for me

**Comment by nodeit** [comment]
I updated the docs to make this a bit more clear. Thanks for pointing this out!

**Comment by Samlilli** [comment]
Thanks for the fast response & updating the docs!

**Comment by nodeit** [comment]
Not a problem!
