### ISSUE TITLE
SHA256

### ISSUE THREAD

**Issue by davidsims9t** [christophergregory/shopify-node-api#48]
I'm using this module with React / Webpack and it works well with exception of the Shopify.exchange_temporary_token() fails because crypto.createHmac('SHA256') is used instead of crypto.createHmac('sha256'). React / Weback uses the crypto-browserify module which requires the hash name to be lowercase.

**Comment by nodeit** [comment]
Can't get to it right now since i'm at work but I'm happy to accept a pull request as long as it passes all tests.

**Comment by nodeit** [comment]
done
