### ISSUE TITLE
include error_description in thrown error messages

### ISSUE THREAD

**Issue by mozeryansky** [christophergregory/shopify-node-api#50]
This is just a feature request.
I could not find an official error response format from Shopify, but the error responses I receive look like this:

> {"error":"invalid_request","error_description":"Could not find Shopify API application with api_key: "}

Currently the library uses the 'error' param as the error message when thrown. I believe all 400 requests are 'invalid_request' errors, and it would be a more descriptive message if it contained the 'error_description' if available.

**Comment by nodeit** [comment]
Sounds like a reasonable feature to me; are you able to provide a pull request? I'm more than happy to merge it in if it's complete with tests.

**Comment by mozeryansky** [comment]
Great! I'll put it on my to do list for now.
