### ISSUE TITLE
Refactor?

### ISSUE THREAD

**Issue by barczaG** [christophergregory/shopify-node-api#52]
Hello guys,

We at [ghostmonitor](https://github.com/ghostmonitor) rely on this repo and want to keep it in good health :) If you you open we could make a refactor using promises generators and [standard](http://standardjs.com/rules.html) style guide. What do you think?

**Comment by nodeit** [comment]
I'm not opposed to a refactor and would certainly welcome newer javascript features; however I have a few hesitations below:

- Do you anticipate any breaking changes to the API?
- Are there new features you want to add?
- Would promises be in addition to callbacks or are you suggesting we switch to them fully? (I would be opposed to the latter)
- Generators require Node > 0.11.x (and requires the use of the --harmony flag in some cases). Are you planning on using Babel to make this repo fully ES5 compatible?

**Comment by barczaG** [comment]
Hi @nodeit, thanks for the fast response :)

1. For now I don't want to make any breaking changes so callbacks would be still supported.
2. For now I have only fixes and better error handling in my mind + better tests.
3. See 1.
4. I would prefer `babel` and `ES7` syntax with `async await` and then we would have legacy support.

**Comment by nodeit** [comment]
@barczaG: all sounds good to me. What's the next step here and do you need anything on my end?

One last thing, in terms of testing I do prefer [tape](https://github.com/substack/tape) but this is not a sticking point for me if you want to stay with mocha/chai.

**Comment by nodeit** [comment]
@barczaG I'm going to close this since it's not an "issue" for now. Feel free to reopen when you are ready to get started or if you have any questions for me.
