### ISSUE TITLE
Shopify’s OAuth flow is changing

### ISSUE THREAD

**Issue by dciccale** [christophergregory/shopify-node-api#55]
Is this change taken into account on the lib?

> Shopify’s OAuth flow is changing
> 
> This is a reminder about a change that we are making to Shopify’s OAuth functionality.
> 
> Effective tomorrow, June 1, the signature URL parameter will not be included in OAuth redirects that come from Shopify. We announced this deprecation in December, 2013 because of security problems with the MD5 algorithm.
> 
> Please take a moment to make sure that your app uses the newer HMAC URL parameter to verify OAuth requests.
> 
> You can find more information about this change in our OAuth documentation and in Shopify’s API Announcements forum.
> 
> If you have any questions or feedback, just reply to this message and we’ll be glad to help.
> 
> Thanks for reading,
> Shopify Apps Team

thanks for the best shopify node module

**Comment by nodeit** [comment]
Yes, this changed happened a few months back. The HMAC parameter is already incorporated into the module, there should be no affect on your current apps.

**Comment by dciccale** [comment]
nice!, I was just checking cause I got still reminder emails. good job and thx
