### ISSUE TITLE
Not using an Error object

### ISSUE THREAD

**Issue by rfink** [christophergregory/shopify-node-api#56]
Hello,

Great module, very helpful.  One question, is there a reason you don't use the native "Error" object?  This module doesn't play well with koa.js, since it expects a native Error object.  Would you be opposed to a P.R. that uses a native Error object?  I would still attach the same properties.  Thanks!

**Comment by nodeit** [comment]
@rfink I'm happy to accept PR as long as they are documented, have tests and don't break anything :)
