### ISSUE TITLE
Hmac verifcation failed

### ISSUE THREAD

**Issue by Talhakh** [christophergregory/shopify-node-api#58]
Hi,

After the OAuth update of shopify my app has stopped working. I checked the issue and its when i call the "exchange_temporary_token" method and I get the error "Signature is not authentic!" now as my code is deployed on github without the node modules I am simply updating my version in the package.json so shouldnt it work?? If not then what is required at my end?? My current code is this

function verifyAndGetToken(req){
	query_params = req.query;
	shopifyApi.exchange_temporary_token(query_params, function(err, data) {
	console.log("REsponse from auth token", err, data);// This line prints the error "Signature is not authentic!"
	AccountDb.findOneAndUpdate({
	"stores.name": req.query.shop
	}, {
	"stores": [{
	name: req.query.shop,
	token: data.access_token
	}]
	}, {
	upsert: true
	}, function(err, account) {
	console.log("Got auth token and updated account", err, account)
	req.session.shopify = query_params;
	console.log("auth token set session",req.session)
	res.redirect('/shopify/')
	return;
	});
	});
}

**Comment by nodeit** [comment]
What ended up being the fix?

**Comment by Talhakh** [comment]
I used the body of the function exchange-temporary-token with the following
check is-valid-signature(params,true)
