### ISSUE TITLE
Listening for Shopify Events?

### ISSUE THREAD

**Issue by daslicht** [christophergregory/shopify-node-api#61]
Hi,
is it possible to listen for Shopify Events ?
see: https://help.shopify.com/api/reference/event

Cheers Marc

**Comment by nodeit** [comment]
You would need to poll for events as this module is simply a nice wrapper for the shopify API. You should look into [webhooks](https://help.shopify.com/api/reference/webhook) which will let you setup endpoints on your own server that will "listen" for events from shopify.
