### ISSUE TITLE
Need a way to have the original request URL in the Shopify.get() response

### ISSUE THREAD

**Issue by mariusa** [christophergregory/shopify-node-api#62]
Sometimes Shopify errors on Shopify.get() responses (e.g. a HTML page saying Something went wrong), and we need to re-try that.

However, as we issue multiple Shopify.get() calls asynchronously, we can't tell which of the original requests failed once we get the response, as the included data doesn't mention the original url.

In
ShopifyAPI.prototype.makeRequest
only the headers are passed to callback:
callback(null, json, response.headers);

Would you please pass the original request URL too?

Thanks

**Comment by nodeit** [comment]
I have included the original request options in the callback so you have access to the original request: c16af70be3d5581ec0bca18c80054b714378da55

**Comment by mariusa** [comment]
Works great, thanks!
