### ISSUE TITLE
webpack error, module not found

### ISSUE THREAD

**Issue by chartotu19** [christophergregory/shopify-node-api#69]
I am using`version : 2.1.0`
Module not found: Error: Cannot resolve 'file' or 'directory' ./package in /Users/Path/to/Project/node_modules/shopify-api-node
 @ ./~/shopify-api-node/index.js 10:12-32

Shouldnt it specially use `json` extension? I am missing something in my webpack config?

```
var webpack = require('webpack');

module.exports = {
    entry: "./index.js",
	target:"node",
    output: {
        path: __dirname,
        filename: "bundle.js"
    },
	resolve: {
		extensions: ['', '.js'],
		modules: [
			'node_modules'
		],
	},
    module: {
        loaders: [
		{test: /\.js$/,
			exclude: [/node_modules/, /.+\.config.js/],
			loader: 'babel-loader',
			query: {
				presets: ['es2015']
			}
		},
		{test: /\.json$/,loader:'json-loader'},
		]
	}
};
```

**Comment by nodeit** [comment]
This appears to be a webpack related question and not a shopify-node-api issue. I'd love to help but I'm only topically familiar with webpack.
