### ISSUE TITLE
Access Token Exchange always returns 'Error: Signature not authentic!'

### ISSUE THREAD

**Issue by MasterDover** [christophergregory/shopify-node-api#73]
I have been pulling my hair out for the past day trying to figure out where I am going wrong, but when i try to get my app setup for public use I just get errors when I try to finish doing the auth, see the relevant code below..

```
router.get('/install', function(req, res, next) {
    shop = req.param('shop');
    Shopify = new shopifyAPI({
        shop: shop, // MYSHOP.myshopify.com
        shopify_api_key: apikey, // Your API key
        shopify_shared_secret: sharedkey, // Your Shared Secret
        shopify_scope: 'read_orders,read_products,read_customers',
        redirect_uri: appurl + '/finish_auth',
        nonce: n() // you must provide a randomly selected value unique for each authorization request
    });
    writeConfigData(shop, Shopify.config); //writes the config to firebase, worried the config was wrong
    var auth_url = Shopify.buildAuthURL();
    res.redirect(auth_url);
});

router.get('/finish_auth', function(req, res){
    var theshop = req.param('shop').replace(/\./g, "_"); //this is just to find the saved shopconfig in firebase
    database.ref('configs/' + theshop).once('value').then(function(snapshot) {
        var config = snapshot.val();
        var Shopify = new shopifyAPI(config), // You need to pass in your config here
            query_params = req.query;
        Shopify.exchange_temporary_token(query_params, function (err, data) {
            // This will return successful if the request was authentic from Shopify
            // Otherwise err will be non-null.
            // The module will automatically update your config with the new access token
            // It is also available here as data['access_token']
            console.log("HERE IS THE EXCHANGE: " + err + data);
        });
    });

});
```

The current Docs are a little fuzzy with is_valid_signature and the way that Shopify uses hmac now instead, I have tried about a thousand different workarounds but always get that same error... I am starting to think it might actually be Shopify.

Any help with this issue would be awesome

**Comment by nodeit** [comment]
What error(s) are you getting?

**Comment by mayconfsousa** [comment]
I'm getting the same error when call the Shopify .exchange_temporary_token method. The object err contains the message 'Error: Signature not authentic!' and object data is undefined.

**Comment by itjustwerks** [comment]
@mayconfsousa ... I'm working on setting up my first public Shopify app, and had the same issue as you with this package. It seems the issue is coming from the use of nonce function in the config parameters. If you generate your nonce before defining your Shopify var, it should work for ya!

```
var nonceVal = n();
var Shopify = new shopifyAPI({
    shop: 'MYSHOP',
   ...
   nonce: nonceVal
});
```

**Comment by bintangadinandra** [comment]
@itjustwerks , I've already defined the nonce right before the shopify var but still doesn't work. The error is still 'Error: Signature not authentic!'. This is my code, mostly same as the doc.

`var router = express.Router();
var n = require('nonce')();
var non = n();

var config = {
  shop: 'shipindo', // MYSHOP.myshopify.com
  shopify_api_key: '<api_key>', // Your API key
  shopify_shared_secret: '<shared_secret>', // Your Shared Secret
  shopify_scope: 'read_products',
  redirect_uri: 'http://localhost:3000/finish_auth',
  nonce: non.toString() // you must provide a randomly selected value unique for each authorization request
};

router.get('/', (req,res) => {
  var Shopify = new shopifyAPI(config);
  res.redirect(Shopify.buildAuthURL());
})

router.get('/finish_auth', (req, res) => {
  // You need to pass in your config here
  var Shopify = new shopifyAPI(config),
      query_params = req.query;

  Shopify.exchange_temporary_token(query_params, function(err, data){
    // This will return successful if the request was authentic from Shopify
    // Otherwise err will be non-null.
    // The module will automatically update your config with the new access token
    // It is also available here as data['access_token']
    if(err) {
      //it allways goes here
      res.send('there is an error');
      console.log(err);
    } else {
      res.send(data)
    }
  });
})`

**Comment by Skoulix** [comment]
@bintangadinandra 

How did you solve this. I have the same issue, I'm getting 'Error: Signature not authentic!' no matter what I do.

Thanks

**Comment by oscargbadou1989** [comment]
@Skoulix 
I think that you must use the same value of nonce on both Shopify config.

**Comment by lfernando-silva** [comment]
for me, the @itjustwerks solution worked.
 
```javascript
const nonce = require('nonce')();

//...config shopify object stuff
nonce: nonce().toString()


````

**Comment by tlchatt** [comment]
Using the same nonce stored in a variable first and the .tostring() function solved this error for me.

**Comment by TahaBoulehmi** [comment]
This worked for me as well:
```javascript
const nonce = require('nonce')();

const config = {
    //...config shopify object stuff
    nonce: nonce().toString()
}
```
