### ISSUE TITLE
API requests don't always return an err for unsuccessful responses

### ISSUE THREAD

**Issue by Ghazgkull** [christophergregory/shopify-node-api#75]
API requests don't always return an err for unsuccessful responses. A simple case is a GET request to an asset that doesn't exist. For example:

`shopifyAPI.get('https://<store>.myshopify.com/admin/themes/<themeid>/assets.json?asset[key]=doesnotexist', function(err, data, headers) {});`

An API call like this results in Shopify sending a response with a 404 status code and an empty body. This should result in the callback being invoked with an err, but instead it gets called with no err and data={}.

The cause of the issue appears to be in shopify.js#makeRequest. This function is relying on JSON body inspection to determine if an error is returned.

Instead, the code should use `response.statusCode` to determine if the request was a success. And then inspect the JSON body just for the purpose of pulling out any additional messages.

**Comment by Ghazgkull** [comment]
Created a pull request that expands the error handling to include all error responses. #76

**Comment by Ghazgkull** [comment]
@nodeit Thanks for merging this in. Really looking forward to getting the improved error handling. Any idea when a release containing this change might be available?

**Comment by nodeit** [comment]
@Ghazgkull done!
