### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by MyronBatiuk** [christophergregory/shopify-node-api#77]
Hi ! I've installed this module to my local app built on angular. I am trying to get some data from my shopify store ( Private App ) to my local http://localhost:4200 . I get this error in console :

"Fetch API cannot load https://mephistoshoesseattle.myshopify.com/admin/products.json. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

I've read a tonn of doc about CORS , but nothing helped.
You are my only hope, please help!

**Comment by nodeit** [comment]
This module is not intended to be used in the browser; with that said, if you want to do it anyway you will need to call the API through a proxy that has CORS disabled. 

This is beyond the scope of what I'm willing to support for this project but there are plenty of resources out there that explain this process. 

In a nutshell, you need create a proxy that is the middleman between the browser and the api. 

Browser -> proxy (with cors disabled) -> API endpoint.

Remember, CORS is a *browser* limitation, so you can create a very simple proxy on your localhost using node that will let your call pass through with no problems.

Best of luck!
