### ISSUE TITLE
Using the checkout uri requires work when a 202 status code is returned

### ISSUE THREAD

**Issue by BKnights** [christophergregory/shopify-node-api#80]
The checkout URI makes use of a 202 response.statusCode and a location header.

shopify-node-api appears to swallow non-error codes.

a simple "fix" would be to add a header in your response.on('end') event handler

`var headers = response.headers;
headers.x-shopify-status = response.statusCode;
callback(error, json, headers, options);`

**Comment by nodeit** [comment]
Hey @BKnights, if you want to issue a pull requests with tests I'm more than happy to merge this in.
