### ISSUE TITLE
Invalid API key or access token

### ISSUE THREAD

**Issue by AviTil** [christophergregory/shopify-node-api#81]
Hi Chris,

Thanks for setting up this module. It's been great so far, however, I have an issue using it.

Once I get my permanent token (it's automatically saved to the access_token property in the config object), I try the following code:

------------
var Shopify = new shopifyAPI(config)
        
Shopify.get('/admin/products.json', function(err, data, headers){
        console.log(data)
    })
------------

config is:
{ shop: 'second-opinions-store',
  shopify_api_key: '167922d6d9ace8e71795cb4c10074cf4',
  shopify_shared_secret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  shopify_scope: 'write_products',
  redirect_uri: 'http://localhost:5000/finish_auth',
  nonce: '150281256017000',
  verbose: true,
  access_token: 'xxxxxxxxxxxxxxxxxxxxxxxxxx' }

I'm sure api_key, shared_secret and access_token are correct for my store, but I get a 401 error: 
 "[API] Invalid API key or access token (unrecognized login or wrong password)"

What am I doing wrong??

**Comment by nodeit** [comment]
Hi @AviTil, 

Thanks for the kind words. I am not sure exactly what is causing the error but the error message is originating from Shopify's API and not from this module. You would need to consult Shopify's API Documentation, Forums and/or Support to resolve this issue.

**Comment by AviTil** [comment]
Hi.. thanks, but in this module, where do the api_key and token actually get used in the makeRequest method (in shopify.js)?

Does one need to explicitly pass them in somewhere when calling Shopify.get?

**Comment by nodeit** [comment]
Once you have an `access_token`, it is used here within the makeRequest method: https://github.com/christophergregory/shopify-node-api/blob/master/lib/shopify.js#L130

The `api_key` is only needed when you are retrieving a new access_token and in that case is used here:

- https://github.com/christophergregory/shopify-node-api/blob/master/lib/shopify.js#L79
- https://github.com/christophergregory/shopify-node-api/blob/master/lib/shopify.js#L32

Again, once you have the `access_token` the api secret/key are no longer required, they are only needed in the initial steps to retrieve a token.
