### ISSUE TITLE
Getting Shop Details

### ISSUE THREAD

**Issue by AviTil** [christophergregory/shopify-node-api#82]
Hi,

In this module, seems like you are setting the Shop: 'MYSHOP' when you create a new shopifyAPI object. However, for a public app, how and where does the application get the shop name of the actual shop trying to install the app? I would assume the buildAuthURL function, exchange temporary token and all of the requests would require the actual shop name, not a hardcoded one?

Thanks for your help.
A

**Comment by nodeit** [comment]
The shop name is one of the pieces of information that the API, and thus this module, expects you to provide. This information will be provided by the customer themselves or by Shopify during the install process from the Shopify app store. (e.g. A customer clicks on your link in the app store and shopify sends your app a link with the shop name appended.)

Shopify's documentation is excellent and explains all of this information here: https://help.shopify.com/api/tutorials

This module is simply a javascript wrapper around the API so I highly recommend reading the documentation in its entirety.
