### ISSUE TITLE
Embedded App Authentication

### ISSUE THREAD

**Issue by celsowhite** [christophergregory/shopify-node-api#84]
I'm creating an embedded app and this wrapper is working well. I don't see any special instructions in the documentation about escaping the iframe. Does this app automatically handle the oAuth redirect for embedded apps through the function res.redirect(auth_url)? Or do I need to add code within my app to escape the iframe? 

Per [Shopify's documentation](https://help.shopify.com/api/sdks/shopify-apps/embedded-app-sdk/getting-started) "it is critical that the initial OAuth request redirect escapes the iframe to make the requests."

**Comment by nodeit** [comment]
Sorry for the delay. You will need to add this code yourself as it is not provided within this module.
