### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by Ghazgkull** [christophergregory/shopify-node-api#85]
Where can I find the change log for shopify-node-api? The last release shown here in the GitHub project is version 1.3.0, but I see version 1.8.0 in NPM.

I'm currently on version 1.7.7 and wondering what's changed.

**Comment by nodeit** [comment]
Hi @Ghazgkull, 

Unfortunately I didn't start out with a change log and it never materialized. The commit messages are the only thing available here. 

Regarding the versioning though, I see 1.8.0 on both github and npm. Can you let me know where you are seeing the discrepancy?

**Comment by Ghazgkull** [comment]
Just looking at the Releases tab from the project home page. It shows up to version 1.3.0 and then stops: https://github.com/christophergregory/shopify-node-api/releases

**Comment by nodeit** [comment]
Fixed
