### ISSUE TITLE
Error: Signature is not authentic!

### ISSUE THREAD

**Issue by alexandprivate** [christophergregory/shopify-node-api#88]
Error: Signature is not authentic!
at ShopifyAPI.exchange_temporary_token (..\node_modules\shopify-node-api\lib\shopify.js:86:25)

This is weird since we are testing this from a shopify store, any idea ?

**Comment by nodeit** [comment]
Hard to say without all the information but I'd make sure that you are providing all the details outlined here: https://help.shopify.com/api/getting-started/authentication/oauth#step-4-making-authenticated-requests

This module is simply a wrapper around the api so it is very unlikely that it's the cause of the error as I'm not seeing other issues like this.
