### ISSUE TITLE
Do something when user creates new cart?

### ISSUE THREAD

**Issue by joshbedo** [christophergregory/shopify-node-api#89]
Trying to figure out how my app can get notified when a user creates a cart sending cart information ( abandoned cart details )

Thanks in advance!

**Comment by nodeit** [comment]
Josh, 

Apologies for the radio silence. What you are looking for are called [Webhooks](https://help.shopify.com/api/reference/webhook). A webhooks is simply an endpoint that you setup that Shopify will call when something happens. Cart activity is one of the event options.

**Comment by joshbedo** [comment]
Got it working thanks for the reference :)
