### ISSUE TITLE
Multiple scope does not redirect to Redirect URL

### ISSUE THREAD

**Issue by 24thdiv** [christophergregory/shopify-node-api#90]
I have this shopify config object where scope is write_products but when I give multiple scopes it's not redirecting to redirect URL.  I give multiple scopes by comma separated values but it's not redirecting to URL.

var configShopify = {
    shop: config.shop,
    shopify_api_key: config.shopify_api_key,
    shopify_shared_secret: config.shopify_shared_secret,
    shopify_scope: 'write_products',
    redirect_uri: 'http://localhost:3000/finish_auth'

};

So How can I give all scopes.

**Comment by nodeit** [comment]
Providing scopes as a comma separated value is the correct way to do it, so there must be something else going on here. 

It's hard to say without any context or error message.
