### ISSUE TITLE
Support Shopify GraphQl call limits

### ISSUE THREAD

**Issue by takinola** [christophergregory/shopify-node-api#98]
I assume this module is compatible with the Shopify GraphQL Admin API (since the authentication mechanism is similar) however, the GraphQL Admin API uses a different rate limiting mechanism.  Is it possible to modify the rate limiting function to support the cost function approach?

**Comment by nodeit** [comment]
Hey @takinola, this module was built years ago with the rest API in mind only. If it works at all with Shopify's Graph implementation then that is pure happenstance. 

I plan on maintaining this module for the rest API as long as I have the time and motivation to do so but I have no intention of adding support for GraphQL as I imagine there are other libraries that already do so. 

With that said, if it is something you are willing to work on and add to this module I am more than happy to merge it in if it works, has tests and is backward compatible with the current implementation.
